// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: pinned_website.proto

package pinned_websitespb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PinnedWebsite struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// @inject_tag: yaml:"value"
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty" yaml:"value"`
}

func (x *PinnedWebsite) Reset() {
	*x = PinnedWebsite{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pinned_website_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PinnedWebsite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinnedWebsite) ProtoMessage() {}

func (x *PinnedWebsite) ProtoReflect() protoreflect.Message {
	mi := &file_pinned_website_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinnedWebsite.ProtoReflect.Descriptor instead.
func (*PinnedWebsite) Descriptor() ([]byte, []int) {
	return file_pinned_website_proto_rawDescGZIP(), []int{0}
}

func (x *PinnedWebsite) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PinnedWebsite) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_pinned_website_proto protoreflect.FileDescriptor

var file_pinned_website_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x69, 0x6e, 0x6e, 0x65, 0x64, 0x5f, 0x77, 0x65, 0x62, 0x73, 0x69, 0x74, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x70, 0x69, 0x6e, 0x6e, 0x65, 0x64, 0x5f, 0x77,
	0x65, 0x62, 0x73, 0x69, 0x74, 0x65, 0x73, 0x22, 0x35, 0x0a, 0x0d, 0x50, 0x69, 0x6e, 0x6e, 0x65,
	0x64, 0x57, 0x65, 0x62, 0x73, 0x69, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x15,
	0x5a, 0x13, 0x2e, 0x3b, 0x70, 0x69, 0x6e, 0x6e, 0x65, 0x64, 0x5f, 0x77, 0x65, 0x62, 0x73, 0x69,
	0x74, 0x65, 0x73, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pinned_website_proto_rawDescOnce sync.Once
	file_pinned_website_proto_rawDescData = file_pinned_website_proto_rawDesc
)

func file_pinned_website_proto_rawDescGZIP() []byte {
	file_pinned_website_proto_rawDescOnce.Do(func() {
		file_pinned_website_proto_rawDescData = protoimpl.X.CompressGZIP(file_pinned_website_proto_rawDescData)
	})
	return file_pinned_website_proto_rawDescData
}

var file_pinned_website_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pinned_website_proto_goTypes = []interface{}{
	(*PinnedWebsite)(nil), // 0: pinned_websites.PinnedWebsite
}
var file_pinned_website_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pinned_website_proto_init() }
func file_pinned_website_proto_init() {
	if File_pinned_website_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pinned_website_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PinnedWebsite); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pinned_website_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pinned_website_proto_goTypes,
		DependencyIndexes: file_pinned_website_proto_depIdxs,
		MessageInfos:      file_pinned_website_proto_msgTypes,
	}.Build()
	File_pinned_website_proto = out.File
	file_pinned_website_proto_rawDesc = nil
	file_pinned_website_proto_goTypes = nil
	file_pinned_website_proto_depIdxs = nil
}
